# Generated by Django 5.2.4 on 2025-07-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="phone",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(default="", max_length=100),
        ),
    ]
